language: node_js
node_js:
  - "node"

before_install:
  - npm install -g typescript@2.6.2

before_script:
  - tsc

script:
  - npm run coverage

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master