// Entity class declaration ---------------------------------------------------
/**
 * Entity classes are used to describe which properties are part of a response body.
 * 
 * This is the Entity base class. This abstract class defines the minimal properties or methods an Entity should have. Extend of this class to create Entity classes for every hypermedia format adapter. For examples, see Siren.Entity or CJ.Collection.
 * 
 * In most cases, the library user does not need to handle Entities manually. The adapter's Provider creates an Entity instance automatically when needed. In certain cases, a user might not want to use the Entity instance generated by a Provider, for example when using a Siren EmbeddedRepresentation. See [Siren EmbeddedResource usage](https://github.com/danepod/movie-database/blob/master/src/resources/movie/list/siren/provider.ts#L27) for a concrete example of this.
 */
export abstract class Entity {
    /**
     * Defines the general behavior how an Entity shall be serialized into JSON. This method can be used to remove properties which you don't want to send in a response body.
     * 
     * @returns An Entity object, containing only properties you wish to send in a response body
     */
    toJSON(): Entity {
        return this;
    };
}